---
- hosts: webhosts
  become: True
  tasks:
  - name: uninstall tomcat8
    apt:
      name: tomcat8
      state: absent
  - name: Install java-webserver
    apt:
      name: tomcat9
      state: present
  - name: Start tomcat9
    service:
      name: tomcat9
      state: started
      enabled: True
  - name: Remove default ROOT app
    file: 
      path: /var/lib/tomcat9/webapps/ROOT/
      state: absent
  - name: Deploy the WAR file
    copy: 
      src: ../app/target/ROOT.war
      dest: /var/lib/tomcat9/webapps/
